onlyBuiltDependencies:
  - "@neja-digital/react-ui"

allowBuilds:
  "@neja-digital/react-ui": true

blockExoticSubdeps: false

minimumReleaseAgeExclude:
  - '@neja-digital/css'
  - '@neja-digital/react-ui'
